name: Laravel Tests
on: [push]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

    - name: Start Laravel Sail
      run: |
        vendor/bin/sail up -d
        vendor/bin/sail artisan migrate

    - name: Run tests
      run: vendor/bin/sail test
