name: Laravel Tests
on: [push]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Set Environment Variables
      run: |
        echo DB_CONNECTION=mysql
        echo DB_HOST=mysql >> .env
        echo DB_PORT=3306 >> .env
        echo DB_DATABASE=pethub_backend_2 >> .env
        echo DB_USERNAME=sail >> .env
        echo DB_PASSWORD=password >> .env
        
    - name: Start Laravel Sail
      run: |
        ./vendor/bin/sail up -d
        ./vendor/bin/sail artisan migrate

    - name: Run tests
      run: ./vendor/bin/sail test
